export const CORE_SERVICES = {
  CONFIG: "config",
  HEALTH: "health",
  PROVIDER_MANAGER: "providerManager",
  DISCOVERY: "discovery",
  ROUTER: "router",
  LOGGER: "logger",
  EVENT_BUS: "eventBus",
  HOOKS: "hooks",
  LIFECYCLE: "lifecycle",
  MODULES: "modules",
  PLUGINS: "plugins",
  DATABASE: "database",
  AUTH: "auth",
	STORAGE: "storage",
	CACHE: "cache",
	QUEUE: "queue",
	SCHEDULER: "scheduler",
	AI: "ai",
	PROVIDER: "provider",
} as const;