import { Router, type Request, type Response } from "express";
import { successResponse } from "../../core/responses/success-response.js";
import { createdResponse } from "../../core/responses/created-response.js";
import { asyncHandler } from "../../core/utils/async-handler.js";
import type { {{pascalName}}Service } from "./{{normalizedName}}.service.js";

/**
 * {{pascalName}} Router — {{description}}
 * Auto-generated by ONBP AI Builder.
 * Routes are domain-specific based on the AI architecture plan.
 */
export function create{{pascalName}}Router(service: {{pascalName}}Service): Router {
  const router = Router();

{{routeHandlers}}
  return router;
}
