# {{pascalName}} Module

> Auto-generated by **ONBP AI Builder** · Domain: _{{description}}_

## Overview

This module was scaffolded by the ONBP AI Builder based on an AI-generated architecture plan.
All route handlers and service method stubs are domain-specific and ready for business logic implementation.

**Enabled ONBP Capabilities:** {{enabledCapabilities}}

---

## API Endpoints

{{readmeRouteTable}}

---

## File Structure

| File | Purpose |
|------|---------|
| `module.ts` | IModule registration — wires repository, service, and router |
| `{{normalizedName}}.router.ts` | Express Router with domain-specific route handlers |
| `{{normalizedName}}.service.ts` | Business logic layer — implement TODO stubs |
| `{{normalizedName}}.repository.ts` | Data access layer — add Drizzle queries |
| `{{normalizedName}}.schema.ts` | Drizzle PostgreSQL table definition |
| `{{normalizedName}}.types.ts` | TypeScript interfaces and DTOs |
| `{{normalizedName}}.events.ts` | Domain event constants |
| `{{normalizedName}}.validation.ts` | Zod validation schemas |

---

## Getting Started

1. **Implement service methods** in `{{normalizedName}}.service.ts` — look for `// TODO` comments
2. **Add Drizzle queries** in `{{normalizedName}}.repository.ts`
3. **Run migrations** if you modified `{{normalizedName}}.schema.ts`
4. **Register the module** in `apps/api/src/bootstrap/register-modules.ts`:

```typescript
import { {{pascalName}}Module } from "../modules/{{normalizedName}}/module.js";
// inside registerModules():
await moduleManager.load(new {{pascalName}}Module());
```

5. **Run the test suite**: `pnpm test`

---

_Generated by ONBP AI Builder — Open Node Backend Platform_
