import type { {{pascalName}}Repository } from "./{{normalizedName}}.repository.js";
import type { EventBus } from "../../core/events/index.js";

/**
 * {{pascalName}}Service — {{description}}
 * Auto-generated by ONBP AI Builder.
 */
export class {{pascalName}}Service {
  constructor(
    private readonly repository: {{pascalName}}Repository,
    private readonly eventBus?: EventBus
  ) {}

  // ── Domain Operations (auto-generated stubs from AI plan) ─────────────────

{{serviceMethods}}
}
