export const LIFECYCLE = {
  CREATED: "CREATED",
  BOOTSTRAPPING: "BOOTSTRAPPING",
  CORE_INITIALIZED: "CORE_INITIALIZED",
  PLUGINS_REGISTERED: "PLUGINS_REGISTERED",
  MODULES_REGISTERED: "MODULES_REGISTERED",
  ROUTES_REGISTERED: "ROUTES_REGISTERED",
  READY: "READY",
  STOPPING: "STOPPING",
  STOPPED: "STOPPED",
} as const;